language: go
go:
- 1.10.x
- 1.11
before_install:
- go get -u github.com/mattn/goveralls
script:
- goveralls -service=travis-ci
git:
  depth: 3
notifications:
  email: false
  slack:
    secure: Iij0OxR+dDghvtYtYZInp9951xjgTmQ/8vew+o3lYQS+sOaK+tnDM8d+O2FrFveaUqZ2jJ/wBFK3zXsPpmFoTu+0u6aj8dIryXMC/61yEQiKJh3MXsLkluNfRnE63HgO40YGnC31QLmx3elEVESIpXc+XTQUjTrIV6QroLjAXCjQslOAbPPxsHq/s7sOuUc2zBMGEAv/EIQYsF21WT6VYYdCV6dlKeahsqXF3Va0P0Ml1lJl195o/tVQyoT6lBSlNnczKw0tIBYEHzOOQ/vm7D2rgRexmMhD81oYycmlrxlUQ7lKxYaMQ63SW+smbtBikAqb5dat2/kYBgrpwIbCzzrLPUp8tBxYdz+Eur0zZqO+zpvGlBDkcbl+r3EmaQZ7Kwuuf+TcCx6uI7c5tfjmlToZoZMA0SIEIHrtu6VpThNoEdYJcTN9pRaCZHmXDeCvrg+zPJbcau4br3uGqzagIfDvREIYTd6l0vcpLjbF2g1E9Ps9iYl2mi7DTsTkv1qbiVoMejTBjZZbKJrXVg5d3kBBOMpRBm+Id43o/6Si75oftJxcczmdZn9iyN79QBEvFqt2VJ3a1ChSjaiW4Qaq81d3c+b6M8PEht9Zip4XGzCGo3uD2VOIlUbOh9GgnsgeIgUkxYbqLzlXxuU1A3HlYe3Tt9odCZmfAvOT/Y6eEk8=
env:
  global:
    - GO111MODULE=on
